### ISSUE TITLE
compare gsl / gnomic

### ISSUE THREAD

**Issue by hredestig** [DD-DeCaF/scrum#122]
get info, can we switch to gsl?

**Comment by hredestig** [comment]
## pro
- large overlap with gsl, cannot find any features in gnomic not supported by gsl
   - except phenes (how should they be translated to constructs?) but level 3 supports gene function
- gsl has the advantage of an intelligent compiler, being able to compile to dna sequence (level 0)
- intuitive attractive level 3 (e.g. 'strong promoter' which leaves the details to the compiler)
- very extensive grammar / integration with parts library
- graphical editor, create valid gsl strings and inspect them directly
- more likely to become widely adopted

## con
- some overhead in adopting as using fsharp, not so intuitive to get running or extending (didn't [manage to install](https://github.com/AmyrisInc/Gslc/issues/1))
- how to generate strings in cameo without ugly dependencies [grammar is largely 1-1 perhaps gnomic could harmonise to gsl syntax?]

**Comment by Midnighter** [comment]
Maybe one of these two tools can help alleviate the F# dependency?

* https://github.com/coquelicot/PyDSL
* https://github.com/neogeny/TatSu

**Comment by hredestig** [comment]
Yes, tatsu (prev grako) is what gnomic uses, writing a gsl parser for python may very well be an option..
