### ISSUE TITLE
Identifier mapping service (preparation)

### ISSUE THREAD

**Issue by phantomas1234** [DD-DeCaF/scrum#14]
Start designing the API and do preparatory work

Minimal viable product:

Replace python dictionary based translation ChEBI IDs with proper service

**Comment by sgalkina** [comment]
after discussion with @henred
MVP should include the following use cases:
Uniprot => SGD
http://prokaryomics.com/ => BIGG
CHEBI => BIGG

Also generally the chain lookup should be supported: if A->C mapping is required, then if A->B->C exists, it should be found. It can be achieved by using graph database like neo4j. CHEBI supports SPARQL querying, making it compatible with this database would help with detecting cases like f.e. glucose in linear form is not detected as carbon source.

**Comment by sgalkina** [comment]
Definition of done: the db technology is chosen, initial setup is made, cameo metanetx dictionary is uploaded there and can be queried in graph manner
