### ISSUE TITLE
As a user of the DD-DeCaF platform I want to use the data available on prokaryomics.com for strain design

### ISSUE THREAD

**Issue by phantomas1234** [DD-DeCaF/scrum#41]
http://prokaryomics.com/
data is available for download
- [x] cleanup media
- [x] cleanup strains
- [x] cleanup fluxomics

**Comment by phantomas1234** [comment]
Should probably be an epic @hredestig.

This is very good reference data for modeling our data backend around. Also strain genotypes could probably be translated into gnomic quite easily.

**Comment by phantomas1234** [comment]
Done when

- [ ] Media
- [ ] Fluxes (Exchange rates + internal fluxes)
- [ ] Strains

are available

**Comment by hredestig** [comment]
start with fluxes then make new cards

**Comment by hredestig** [comment]
Data processing done but upload is blocked as iloop with omics support not yet merged to stable branch and therefore not available in decaf production
