### ISSUE TITLE
Add to_str method to biosustain/gnomic-python

### ISSUE THREAD

**Issue by phantomas1234** [DD-DeCaF/scrum#5]
Extend https://github.com/biosustain/gnomic-python with a to_text function that translates gnomic definitions into human readable text (https://github.com/biosustain/iloop-frontend/blob/36080d74c23c8b4f73749cda764760c357d9ddf1/src/app/common/genotype.js might be a good starting point)

**Comment by warlink** [comment]
Fix have been merged in
