### ISSUE TITLE
As Konstantin I want to see FVA results for my yeast design data on the platform

### ISSUE THREAD

**Issue by phantomas1234** [DD-DeCaF/scrum#75]

**Comment by phantomas1234** [comment]
Dependency: #5 in DD-DeCaF/module-pathways

Done when:

- [ ] Konstantin attended a review

**Comment by hredestig** [comment]
data has been uploaded and can be visualized on the map but
- the default yeast map is not great
- without some kind of sample comparison mode, there is precious little one can hope to see from looking at these maps :(

**Comment by hredestig** [comment]
something wrong here still... reaction PDHm when I compute locally has flux 0.7 but nd (along with almost all other reactions as well) in the app
